// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt5_KkwVXovKbEjzAtUpctsvAP6WTW8ww',
    appId: '1:32352475071:web:8d0867834c508075edf30a',
    messagingSenderId: '32352475071',
    projectId: 'qr-attandance',
    authDomain: 'qr-attandance.firebaseapp.com',
    storageBucket: 'qr-attandance.appspot.com',
    measurementId: 'G-KK7562BVQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6MPxbXWP3mE90eXhl1P_5ntcqw-22QB0',
    appId: '1:32352475071:android:f3ce14a7d6f97a0eedf30a',
    messagingSenderId: '32352475071',
    projectId: 'qr-attandance',
    storageBucket: 'qr-attandance.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCImDeWigJcedcVy_Wok1WMLEnlto1Aqes',
    appId: '1:32352475071:ios:9cf8d4bf6d7e5574edf30a',
    messagingSenderId: '32352475071',
    projectId: 'qr-attandance',
    storageBucket: 'qr-attandance.appspot.com',
    iosClientId: '32352475071-v33ijek0jnf0ou074h6ckukutoqru75q.apps.googleusercontent.com',
    iosBundleId: 'com.example.attandanceQr',
  );
}
